# There is no "true" most-general way to define data. There are advantages and
# disadvantages to each formulation. Instead what we want are a few workable
# components. When helpful, one can convert between them or define new formulations.
# *Why* is there no unique representation? There is only one physical object, so
# we should be able to just represent it with the coordinates of each of the atoms.
# However, this is impractical. First, we don't even know what this is. It's very hard
# to measure. Second, even if we knew what this was, we would need to perform a
# calculation to get what we wanted to know about it to accomplish our objective.

# Fundamental components
component:
- component
- description: >
    If an entity has a "component" component, then it can be a component itself.
    A requirement for components is that if they require another entity
    for their definition, then that entity must be a component of the component.
    Alternatively, a would-be component can be part of a parent component alongside
    the component it depends on.
- data:
    multiplicity [str]:
        description: >
            Allowed number of instances of a component per
            entity.
        default: 0..*

field:
- component
- description: A single attribute or column.
- data:
    name [str]: Name of the field.
    type [entity]: Entity this field is an instance of.
    description [description]: A description of the field.
    multiplicity [str] = "0..*": "Number of instances of field. TODO: Delete?"
    default [entity]: Default value for the field

description:
- component
- description: Widely-used component that describes the entity in question.
- data:
    description [str]: The actual field containing the description.

data:
- component
- description: >
    Component used to define data associated with instances of a component.
    Any entity that owns a data component is assumed to be a component itself.

case:
- component
- description: >
    Component used to document if/elif/else statements.
- data:
    input [str]: Component entity that is the input for the case statement.
    cases [dict[str, str]]: Case statement. Can be nested.

# Relationship components

source:
- component
- description: A source entity used for describing relationships.
- data:
    source [entity]:

target:
- component
- description: A target entity used for describing relationships.
- data:
    target [entity]:

links:
- component
- description: >
    A description of multiple links, using the syntax:
      source --> target
      second_source --> second_target
- data:
    edges [str]: A string that describes the edges, in the 
    link_type [entity]: >
      The type of the links. Must be a component that has either a source and target
      component or a link component.

link:
- component
- description: >
    A component that describes a generic link between two entities.
- data:
    source [source]: The source entity.
    target [target]: The target entity.

dependency:
- component
- description: Indicates that the target depends on the source.
- data:
    source [source]: Source entity.
    target [target]: Target entity.
    data [data]: >
      The types and descriptions for any data being passed between entities.
      Subtlety: by including data as one of the component fields, all instances of
      a dependency are themselves a component definition. This is good, because
      the different instances of the component describe different instances of the
      dependency in action.

alternative_to:
- component
- description: >
    If an entity has this component, then the entity is an alternative to the
    indicated entity.
- data:
    alternative_to [entity]:

references:
- component
- description: Describes relationships between fields in components

# Descriptive components

tag:
- component
- description: >
    When a component owns a tag component as part of its definition, then the component
    describes information on how the owning entity should be treated.

task:
- component
- description: If owned, the entity is a task to complete.

input:
- component
- description: Component representing input.
- data:
    input [data]: >
        Input component instances for the task. Is of type "data", so will be parsed
        in the same manner.

output:
- component
- description: Component representing output.
- data:
    output [data]: >
        Output component instances for the task. Is of type "data", so will be parsed
        in the same manner.

workflow:
- component
- description: If owned, the entity describes a series of tasks to run in order.

trigger:
- component
- description: If owned, the entity can be triggered by the event described.
- data:
    trigger [entity]:

requirement:
- component
- description: If owned, the owner is mandated for the system to function.

status:
- component
- description: Implementation progress status for an entity.
- data:
    status [categorical]:
        categories:
            - new
            - in design
            - in progress
            - in review
            - closed
            - removed

time_dependent:
- component
- description: Description of how the data depends on time.
- data:
    scd_type [categorical]:
        description: Slowly-changing dimension type.
        default: Type II

timestamp:
- component
- description: A specific moment in time.
- data:
    timestamp [str]: String representation of the timestamp.
    seconds [float]: Epoch time representation of the timestamp.
    timezone [categorical]: Timezone for the timestamp.

person:
- component
- description: An entity representing a person.
- data:
    first_name [str]:
    last_name [str]:
    data_of_birth [timestamp]: