meta_parse_system_workflow:
- description: How a manifest is parsed.
- links:
    links: |
            extract --> transform

            subgraph extract_from_files_loop
            extract_from_files --> extract_from_stream

      
