flowchart TD

    subgraph extract
        open_file --> extract_from_stream
        extract_from_stream --> update_registry
        update_registry --> open_file
    end

    extract -->|registry| transform
    
    subgraph transform
        base_transform --> parsecomp_component
        parsecomp_component --> parse_all_components
    end

    