# Requirements
receive_request:
  - requirement
  - task
retrieve_requested_data_from_cloud:
  - requirement
  - task
export_product:
  - requirement
  - task

# Tasks
create_azdo_resources:
  - task
refine_request:
  - task

# Workflow
workflow:
  - flow:
      edges: |
        receive_request --> create_azdo_resources
        create_azdo_resources --> refine_request