# Requirements
accept_request:
  - description: >
      We should be able to receive a request, initiating the process.
  - requirement
  - task
build_product:
  - description: >
      The actual work on the product itself.
  - task
deliver_product:
  - description: >
      After completing the request, viewers should be able to request the product
      at their preferred time.
  - requirement
  - task

# Workflow
global_workflow:
  - workflow
  - links: >
      accept_request --> build_product
      build_product --> deliver_product