# Requirements
accept_request:
- description: >
    We should be able to receive a request, initiating the process.
- requirement
- task

deliver_report:
- description: >
    After completing the request, viewers should be able to request the report
    at their preferred time.
- requirement
- task

# Implementation
request_workflow:
- workflow: >
    accept_request --> build_report
    build_report --> deliver_report

build_report:
- description: >
    The actual work on the report itself.
- task
- workflow: >
    define_report --> set_up_environment
    set_up_environment --> set_up_report
    set_up_report --> work_on_report
    work_on_report --> get_feedback
    get_feedback --> work_on_report
    get_feedback --> finalize_report

set_up_report:
- task
- description: Set up the file structure for a report, including a template.
- status: design

run_report:
- description: Run the code to generate a report.
- task
- workflow: >
    run_etl --> run_report_notebook
    run_cohort_notebook --> run_report_notebook

run_report:
- alternate_definition
- description: Run the code to generate a report.
- task
- algorithm: >
    sorted_report_code = report_code.sort("execution_priority")
    for code in sorted_report_code:
      notebook.run(code)

cohort_notebook:
- description: A notebook containing the code to define the cohort for a report.

report_notebook:
- description: A notebook containing the code to generate a report table for a report.

report_table:
- description: >
    A table containing the selected data elements for a report. There can be multiple.

pbi_report:
- description: The Power BI dashboard.