# Implementation
request_workflow:
- description: The overall workflow.
- links:
    links: |
      accept_and_define_request -->|request| build_report
      build_report -->|report| deliver_report
    link_type: dependency

accept_and_define_request:
- todo: >
    Change to accomodate working on the request prior to DS approval and prior to the
    service agreement, as needed.
- task
- links:
    links: |
      submit_intake_form -->|request| create_azdo_ticket
      create_azdo_ticket -->|request.azdo_id| assign_analyst
      assign_analyst -->|request.analyst| get_data_steward_approval
      get_data_steward_approval -->|request.is_approved| add_request_to_backlog

      analyst_is_power_user([analyst_is_power_user?])

      assign_analyst -->|request.analyst| analyst_is_power_user
      analyst_is_power_user -->|no| complete_service_agreement
      analyst_is_power_user -->|yes| add_request_to_backlog
      complete_service_agreement -->|request.is_defined| add_request_to_backlog

      add_request_to_backlog --> build_report
    link_type: dependency

build_report:
- task
- links:
    links: |
      accept_and_define_request -->|request| prepare_report_for_work

      prepare_report_for_work -->|report| work_on_report
      work_on_report --> submit_pr

      all_reviewers_approve([all_reviewers_approve?])

      submit_pr -->|pr| get_feedback
      get_feedback --> all_reviewers_approve
      all_reviewers_approve -->|yes| merge_pr
      all_reviewers_approve -->|no| update_report
      update_report --> get_feedback
      merge_pr --> deliver_report

    link_type: dependency

deliver_report:
- task
- links:
    links: |
      build_report -->|report| deployment_complete

      deployment_complete([deployment_complete?])

      deployment_complete -->|no| wait
      wait --> deployment_complete
      deployment_complete -->|yes| share_link_with_requester
    link_type: dependency

define_report:
- task
- description: Define the report products to be delivered, etc.

set_up_environment:
- task
- description: Set up the environment used to create the report.

set_up_report:
- task
- description: Set up the file structure for a report, including a template.
- status: design

work_on_report:
- task
- description: Make progress on producing the report products defined in define_report.

get_feedback_on_report:
- task
- description: Get feedback on the report in progress.

finalize_report:
- task
- description: Close out the PR for the report.

run_report:
- description: The steps to run the code to generate a report.
- task
- links:
    links: |
      run_etl --> run_cohort_notebook
      run_cohort_notebook --> run_report_notebook
    link_type: dependency

run_etl:
- description: Run any ETL needed for the report.
- task

run_cohort_notebook:
- description: Run the notebook that selects the cohort.

run_report_notebook:
- description: Run the notebook that produces the report tables.

run_report_algorithm_version:
- alternative_to: run_report
- description: Run the code to generate a report.
- task
- algorithm: >
    sorted_report_code = report_code.sort("execution_priority")
    for code in sorted_report_code:
      notebook.run(code)

report_string_formatter:
- case:
    case: >
        report.irb_rank == 1:
            report.product == cohort_notebook : reports/{irb_number}/cohort{optional_label}.py
            report.product == report_notebook: reports/{irb_number}/report{optional_label}.py
            report.product == report_table: reports/{irb_number}/report{optional_label}.py
        report.irb_rank > 1:
            file == cohort_notebook: reports/{irb_number}/cohort.py
    input: report