# Implementation
request_workflow:
- description: The overall workflow.
- links:
    links: |
            accept_request --> build_report
            build_report --> deliver_report
    link_type: dependency

accept_request_workflow:
- append_to: accept_request
- description: >
    We should be able to receive and assign a request, initiating the process.
- input:
    requester [person]: The person seeking to submit a request.
- output:
    request [request]: The formalized request.
    initialized_report [report]: Incomplete report.
    analyst [person]: The analyst or power user working on the request
- links:
    links: |
        submit_intake_form --> assign_analyst
        assign_analyst --> submit_for_data_steward_approval
        submit_for_data_steward_approval --> data_steward_reviews_request
        data_steward_reviews_request -->|approve| analyst_initiaties_report
        data_steward_reviews_request -->|reject| requester_revises_request
        requester_revises_request --> data_steward_reviews_request
            create_or_revise_service_agreement --> requester_reviews_service_agreement
    link_type: dependency

build_report_workflow:
- description: The workflow for building a report
- task
- links:
    links: |
            define_report --> set_up_environment
            set_up_environment --> set_up_report
            set_up_report --> work_on_report
            work_on_report --> get_feedback_on_report
            get_feedback_on_report --> work_on_report
            get_feedback_on_report --> finalize_report
    link_type: dependency

work_on_report:
- description: The workflow for actually working on the report.
- task
- links:
    links: |
        build_cohort --> build_report
        build_report --> build_pbi_report
    link_type: dependency

get_feedback_on_report:
- task
- links:
    links: |
        run_report_with_stg_workflow --> update_pbi_data_connections
        update_pbi_data_connections --> publish_pbi_to_stg
        publish_pbi_to_stg --> submit_pr
        submit_pr --> get_feedback_from_first_reviewer
        get_feedback_from_first_reviewer --> revise_pr
        revise_pr --> get_feedback_from_first_reviewer
        get_feedback_from_first_reviewer --> get_feedback_from_second_reviewer
        get_feedback_from_second_reviewer --> revise_pr
        revise_pr --> get_feedback_from_second_reviewer
    link_type: dependency

finalize_report:
- task
- links:
    links: |
        publish_pbi_to_prd --> update_prd_pbi_with_prd_parameters
        update_prd_pbi_with_prd_parameters --> validate_prd_report
        merge_pr --> run_report_with_prd_workflow
        run_report_with_prd_workflow --> validate_prd_report

deliver_report:
- task
- links:
    links: |
        deploy_report --> run_report
        run_report --> share_report

run_report:
- description: The steps to run the code to generate a report.
- task
- links:
    links: |
            run_etl --> run_cohort_notebook
            run_cohort_notebook --> run_report_notebook
    link_type: dependency

run_etl:
- description: Run any ETL needed for the report.
- task

run_cohort_notebook:
- description: Run the notebook that selects the cohort.

run_report_notebook:
- description: Run the notebook that produces the report tables.

run_report_algorithm_version:
- alternative_to: run_report
- description: Run the code to generate a report.
- task
- procedure: >
    sorted_report_code = report_code.sort("execution_priority")
    for code in sorted_report_code:
            notebook.run(code)

report_string_formatter:
- case:
    case: >
        report.irb_rank == 1:
            report.product == cohort_notebook : reports/{irb_number}/cohort{optional_label}.py
            report.product == report_notebook: reports/{irb_number}/report{optional_label}.py
            report.product == report_table: reports/{irb_number}/report{optional_label}.py
        report.irb_rank > 1:
            file == cohort_notebook: reports/{irb_number}/cohort.py
    input: report

assignment_workflow:
- links:
    links: |
        identify_type_of_request -->|imaging, power-users, RHLCC| edw_manager_submits_for_approval

turn_on_pbi_refresh:
- description: >
    Needs to be done as part of deployment. Currently only can be done by workspace 
    members, which is a bottleneck.
- task