# Requirements
accept_request:
- description: >
    We should be able to receive a request, initiating the process.
- requirement
- task

deliver_report:
- description: >
    After completing the request, viewers should be able to request the report
    at their preferred time.
- requirement
- task

# Implementation
request_workflow:
- workflow: >
    accept_request --> build_report
    build_report --> deliver_report

build_report:
- description: >
    The actual work on the report itself.
- task
- workflow: >
    define_report --> set_up_environment
    set_up_environment --> set_up_report
    set_up_report --> work_on_report
    work_on_report --> get_feedback
    get_feedback --> work_on_report
    get_feedback --> finalize_report

set_up_report:
- task
- description: 
- status: design

report_notebook:
- description: The notebook containing the code to build the data report.

cohort_notebook:
- description: The notebook containing the code to define the cohort.