tag:
- component
- description: >
    When a component owns a tag component as part of its definition, then the component
    describes information on how the owning entity should be treated.

workflow:
- component
- description: If owned, the entity describes a series of tasks to run in order.

trigger:
- component
- description: If owned, the entity can be triggered by the event described.
- fields:
    trigger [entity]:

status:
- component
- description: Implementation progress status for an entity.
- fields:
    status [categorical]:
        categories:
            - new
            - in design
            - in progress
            - in review
            - closed
            - removed

time_dependent:
- component
- description: Description of how the data depends on time.
- fields:
    scd_type [categorical]:
        description: Slowly-changing dimension type.
        default: Type II

timestamp:
- component
- description: A specific moment in time.
- fields:
    timestamp [str]: String representation of the timestamp.
    seconds [float]: Epoch time representation of the timestamp.
    timezone [categorical]: Timezone for the timestamp.

person:
- component
- description: An entity representing a person.
- fields:
    first_name [str]:
    last_name [str]:
    data_of_birth [timestamp]:

case:
- component
- description: >
    Component used to document if/elif/else statements.
- fields:
    case [dict[str, str]]: Case statement. Can be nested.
    input [input]: Component entity that is the input for the case statement.