infrastructure:
- description: >
    If owned, the owner is a set of technologies, functions, people, etc. defined by
    a manifest and created to satisfy one or more requirements.
- component

requirement:
- description: >
    If owned, the owner is a condition an infrastructure is designed around fulfilling.

    A requirement entity is satisfied if:
        1. All child requirements have a status "done" or "cancelled".
- component
- fields:
    value [entity]: The infrastructure this requirement is for.

status:
- description: Tracks progress.
- component
- fields:
    value [str]:
        categories:
            - new
            - in design
            - in development
            - in review
            - done
            - on hold
            - cancelled

satisfies:
- description: The source (owner) entity satisfies the target entity.
- component
- link_type
- fields:
    value [entity]: The [requirement] entity the owner entity satisfies.

supports:
- description: The source (owner) entity supports the target entity.
- component
- link_type
- fields:
    value [entity]: The entity the owner entity supports.

task:
- description: >
    If owned, the entity is a task to complete. Fully-implemented tasks can take a few
    forms:
        1. A function, likely in Python.
        2. A Directed Acyclic Graph (DAG).
        3. A written procedure.
    All above require an task executor.
- component

procedure:
- description: A process for completing a task.
- component
- fields:
    value [str]: Procedure in written format, following no particular guidelines.

input:
- description: Component representing input.
- component
- fields:
    value [id]: >
        Input component instances for the task. Is of type "fields", so will be parsed
        in the same manner.

output:
- description: Component representing output.
- component
- fields:
    value [id]: >
        Output component instances for the task. Is of type "fields", so will be parsed
        in the same manner.

fully_designed:
- description: >
    Each [requirement] entity has at least one [satisfies] entity.
- requirement

fully_designed_test:
- description: If this test passes then the fully_designed requirement is fulfilled.
- test:
    implementation: iac_sketch.validate.ValidationSystem.validate_designed
- satisfies: fully_designed
- status: "in development"

fully_implemented:
- description: >
    Each [requirement] entity has at least one [satisfies] entity and they must
    meet the following conditions:
    1. If a [test] entity, it must have an implementation that passes when executed.
    2. If a [task] entity, it must have a status of "done".
- requirement

fully_implemented_test:
- description: If this test passes then the fully_implemented condition is fulfilled.
- test:
    implementation: iac_sketch.validate.ValidationSystem.validate_implemented
- satisfies: fully_implemented
- status: "in development"

fully_defined:
- description: All [compdef] entities are defined and valid.
- requirement

fully_defined_test:
- description: If this test passes then the fully_defined condition is fulfilled.
- test:
    implementation: iac_sketch.validate.ValidationSystem.validate_defined
- satisfies: fully_defined
- status: "in development"

fully_connected:
- description: >
    The network composed of [link] components and entities as nodes is fully connected.
- requirement

fully_connected_test:
- description: If this test passes then the fully_connected condition is fulfilled.
- test:
    implementation: iac_sketch.validate.ValidationSystem.validate_connected
- satisfies: fully_connected
- status: "in development"