receive_request:
  - resource: task
create_story:
  - resource: task
create_branch:
  - resource: task
workflow:
  - resource: flow
    edges: |
      receive_request --> create_story
      create_story --> create_branch