receive_request:
  - r: task
create_azdo_resources:
  - r: task
refine_request:
  - r: task
workflow:
  - r: flow
    edges: |
      receive_request --> create_azdo_resources
      create_azdo_resources --> refine_request